Agreement Screen
askvortsov1/djangosaml2idp pull request #6
Opened 2019-03-23 05:58 UTC by peppelinux

https://github.com/OTA-Insight/djangosaml2idp/issues/31

2019-03-23 06:02 UTC, peppelinux commented
I also resolved a confict in views.py, please do accurate tests. We should not put bugs in master branch anymore and moving to development branch starting from the next commit!

2019-03-23 17:52 UTC, askvortsov1 commented
> I also resolved a confict in views.py, please do accurate tests. We should not put bugs in master branch anymore and moving to development branch starting from the next commit!

I think you're absolutely right. I would propose the following plan:
1. We code review this PR and make changes as necessary
2. I start a new branch for adding comprehensive automated tests.
3. We confirm that the comprehensive tests are operational
4. We then merge this PR with the added safety net of aforementioned tests.

2019-03-23 23:22 UTC, peppelinux commented
https://github.com/askvortsov1/djangosaml2idp/commit/50178fe135ff79791b8807f3a17c739dcbd11eaf

2019-03-24 00:39 UTC, askvortsov1 commented
I updated the base branch to dev, so that we can continue our discussion here.

2019-03-24 00:50 UTC, peppelinux commented
If you make other commits this PR will go always in conflict and this will increase our work. Please merge it first

2019-03-24 00:57 UTC, peppelinux commented
It went well here: https://github.com/askvortsov1/djangosaml2idp/pull/6/checks?check_run_id=83628791

then you made other commits and now this PR fails pylama, please put a patch here soon as possibile, I have to deal with our real roadmap, I know that you understand

2019-03-24 01:14 UTC, askvortsov1 requested changes
> It went well here: https://github.com/askvortsov1/djangosaml2idp/pull/6/checks?check_run_id=83628791
> 
> then you made other commits and now this PR fails pylama, please put a patch here soon as possibile, I have to deal with our real roadmap, I know that you understand

I've resolved the code style errors in master. As I've said before, I don't want to merge your PR yet because there are a lot of issues that I disagree about. For instance:

1. Using Django forms instead of hardcoding an HTML form
2. Moving out the function to put POST/GET params in request.session into a decorator
3. Implementing any sort of login form

Please take a look at the comments I have left on your PR addressing all these issues. Once we come to an agreement, I will be more than happy to merge your PR.

2019-03-24 01:14 UTC, askvortsov1 commented on README.rst
> +    SAML_IDP_AGREEMENT_MSG = ("Businesses will have to provide the following information to internet users when seeking their consent.")
I don't see the benefit of putting this into config. If someone wants to override it, they can just override the template (which they should do anyway).

2019-03-24 01:14 UTC, askvortsov1 commented on README.rst
> +            'display_agreement_message': "Customized agreement data consent message here",
See previous message. This seems like something that should be in a template, not in settings. And I don't see the use case of overriding this per-SP.

2019-03-24 01:14 UTC, askvortsov1 commented on README.rst
> -    SAML_IDP_SHOW_USER_AGREEMENT_SCREEN = True
Moving this up higher is a good idea

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/admin.py
> +                    'created',
I don't see the benefit of splitting "date" into "created" and "modified".

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/decorators.py
> +def store_params_in_session(request):
I don't see the benefit of making this into a decorator. I wouldn't be against moving this function into utils.py, but making it a decorator seems like overengineering

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/forms.py
> +class AgreementForm(forms.Form):
I don't think we need a Django form for this. It's simple enough that we should just write it into the HTML template (as my solution originally did).

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/forms.py
> +class LoginForm(AuthenticationForm):
As I've mentioned before, I am very very against including login in this app. This app is currently agnostic to the login system used, and I think it'd be better to keep it that way.

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/migrations/0001_initial.py
> -                ('sp_entity_id', models.TextField()),
I set this up as TextField because the max length for uris is about 2000, but most URIs are way under that, so I didn't want to waste the extra memory. What's the benefit of setting it to CharField?

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/migrations/0002_auto_20190322_1457.py
> +        migrations.RemoveField(
See my comment below.

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/models.py
> -    date = models.DateTimeField(default=timezone.now)
My implementation does not need separate date created and date modified fields. Please explain how having 2 fields for date is better than having one.

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/models.py
> +        return '{}, {}'.format(self.user, self.modified)
sp_entity_id should be included in here somewhere

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/templates/djangosaml2idp/login.html
> +        {% csrf_token %}
This template is not used as an actual login form (the file name is misleading and should be renamed). It's a vehicle to send a POST request with the SAMLResponse to the SP through the user's browser. Because of the LoginRequiredMixin, the user is already logged in by this stage.

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/templates/djangosaml2idp/user_agreement.html
> -        <input type="submit" name="confirm" value="Yes" />
Hardcoding the HTML form is much simpler than generating it with Django, and has no detriments. Why do you want to generate it?

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/templates/djangosaml2idp/user_agreement.html
> +        <p>{{ sp_display_agreement_message|safe }}</p>
Why is this one passed through |safe and not the others?

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/urls.py
> +    path('login/', views.LoginAuthView.as_view(), name='login'),
As I've said numerous times in issues and comments, this app should not try to enforce a login solution.

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/views.py
> +from django.contrib.auth.views import LoginView
See comments about login above

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/views.py
> +from .forms import AgreementForm, LoginForm
As I've mentioned before, i see no benefit to using Django-generated forms for the agreement form. LoginForm shouldn't be here in the first place

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/views.py
> +            for k, v in self.processor.create_identity(request.user, self.sp['config']).items()
Good catch, sorry about this.

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/views.py
> +            self.sp['config'].get('display_agreement_message', _(settings.SAML_IDP_AGREEMENT_MSG))
I don't think this is the appropriate place to put the translate tag. Also, as I've mentioned before, I don't see why the agreement_message needs to be defined in settings. It should just be in the template.

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/views.py
> +class LoginAuthView(LoginView):
We should not be trying to implement this.

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/views.py
> +        except Exception as excp:
This part is a good idea.

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/views.py
> +    def get(self, request, *args, **kwargs):
Aside from catching the exception (which should then raise another exception)

2019-03-24 01:14 UTC, askvortsov1 commented on djangosaml2idp/views.py
> +        confirm = int(request.POST.get('confirm'))
This is messier than what was here before.

2019-03-24 08:29 UTC, peppelinux commented
Hi, I disagree about many points so I decide to continue development on my fork. We Will continue to talk about a conceptual roadmap on the master project. If you like something of mine you can Always do a cherry pick.

I develop in Django for about 11 years and I want to be clear:
HTML form should not be hardcoded :)

In your commits I had to fix a lot of bugs, wasting previous time, I cannot follow your tastes because I have a deadline! I made my part, It was very fun. Bye

2019-03-25 23:58 UTC, askvortsov1 commented
> Hi, I disagree about many points so I decide to continue development on my fork. We Will continue to talk about a conceptual roadmap on the master project. If you like something of mine you can Always do a cherry pick.
>
> I develop in Django for about 11 years and I want to be clear:
> HTML form should not be hardcoded :)
> 
> In your commits I had to fix a lot of bugs, wasting previous time, I cannot follow your tastes because I have a deadline! I made my part, It was very fun. Bye

It's been very fun working with you as well! Now that I've finally figured out cherry-pick, I'll be sure to merge some of your commits. I apologize about the bugs I caused; I've now gone through and added significantly more comprehensive unit tests (we're looking at about 95% code coverage). This should prevent more stupid bugs in the future. 

After giving it a bit more thought, I've come to agree on your point regarding hardcoding forms. I've only really been programming for about a year, so I'm somewhat held back by the beginner "less code is better" mentality. I'll cherry-pick your commit with the Django form implementation. 

I still don't think it's appropriate for this project to force a login solution onto developers. The way I see it, a more elegant option to give them the ability to withdraw consent would be through a form/portal, similarly to the way Google Login does it.

Regardless, it's been a pleasure working with you! Although our branches will be splitting off, I hope we'll be able to collaborate in the future, whether on this project or on others.

2019-03-26 08:38 UTC, peppelinux commented
I prefer a specialized login for that check box that permits the user to renew their consent to the data. I will also share this with the oidc provider. I'll cherry pick your unit test as they come

2019-03-26 11:43 UTC, askvortsov1 commented
> I prefer a specialized login for that check box that permits the user to renew their consent to the data. I will also share this with the oidc provider. I'll cherry pick your unit test as they come

My problem isn't as much that you're adding in this feature (which your use case requires). I just think it should be shipped and advertised as an optional feature, not something that the rest of the project depends on, and that this should be made clear in the documentation.

2019-03-28 14:50 UTC, closed without merging